import {
  adjacentHexes,
  type HexCoordinate,
  type HexTerrain,
} from "@gettysburg/game";

// Owner-approved worksheet, 2026-09-06. Inferred links are explicitly enumerated
// below; adjacent woods do not connect merely because both hexes contain trees.
export const TERRAIN_REVISION = "gettysburg-painted-terrain-v1";

const rows = [
  ["A1", "hill", 2, true, 2],
  ["A2", "clear", 0, false, 0],
  ["A3", "clear", 0, false, 0],
  ["A4", "woods", 2, true, 0],
  ["A5", "woods", 2, true, 0],
  ["A6", "woods", 2, true, 0],
  ["A7", "woods", 2, true, 0],
  ["A8", "clear", 0, false, 0],
  ["A9", "clear", 0, false, 0],
  ["A10", "clear", 0, false, 0],
  ["A11", "clear", 0, false, 0],
  ["B1", "woods", 2, true, 0],
  ["B2", "woods", 2, true, 0],
  ["B3", "clear", 0, false, 0],
  ["B4", "woods", 2, true, 0],
  ["B5", "woods", 2, true, 0],
  ["B6", "woods", 2, true, 0],
  ["B7", "clear", 0, false, 0],
  ["B8", "clear", 0, false, 0],
  ["B9", "clear", 0, false, 0],
  ["B10", "clear", 0, false, 0],
  ["B11", "clear", 0, false, 0],
  ["C1", "woods", 2, true, 0],
  ["C2", "clear", 0, false, 0],
  ["C3", "hill", 2, false, 2],
  ["C4", "woods", 2, true, 0],
  ["C5", "woods", 2, true, 0],
  ["C6", "woods", 2, true, 0],
  ["C7", "woods", 2, true, 0],
  ["C8", "woods", 2, true, 0],
  ["C9", "woods", 2, true, 0],
  ["C10", "woods", 2, true, 0],
  ["C11", "woods", 2, true, 0],
  ["D1", "clear", 0, false, 0],
  ["D2", "clear", 0, false, 0],
  ["D3", "woods", 2, true, 0],
  ["D4", "clear", 0, false, 0],
  ["D5", "woods", 2, true, 0],
  ["D6", "woods", 2, true, 0],
  ["D7", "clear", 0, false, 0],
  ["D8", "woods", 2, true, 0],
  ["D9", "woods", 2, true, 0],
  ["D10", "woods", 2, true, 0],
  ["D11", "woods", 2, true, 0],
  ["E1", "clear", 0, false, 0],
  ["E2", "clear", 0, false, 0],
  ["E3", "woods", 2, true, 0],
  ["E4", "woods", 2, true, 0],
  ["E5", "woods", 2, true, 0],
  ["E6", "rough_hill", 4, false, 4],
  ["E7", "rough_hill", 4, false, 4],
  ["E8", "clear", 0, false, 0],
  ["E9", "woods", 2, true, 0],
  ["E10", "clear", 0, false, 0],
  ["E11", "woods", 2, true, 0],
  ["F1", "clear", 0, false, 0],
  ["F2", "clear", 0, false, 0],
  ["F3", "woods", 2, true, 0],
  ["F4", "woods", 2, true, 0],
  ["F5", "rough_hill", 4, true, 2],
  ["F6", "rough_hill", 4, true, 2],
  ["F7", "rough_hill", 4, true, 2],
  ["F8", "clear", 0, false, 0],
  ["F9", "clear", 0, false, 0],
  ["F10", "clear", 0, false, 0],
  ["F11", "woods", 2, true, 0],
  ["G1", "clear", 0, false, 0],
  ["G2", "clear", 0, false, 0],
  ["G3", "clear", 0, false, 0],
  ["G4", "hill", 2, false, 2],
  ["G5", "woods", 2, true, 0],
  ["G6", "rough_hill", 4, false, 4],
  ["G7", "rough_hill", 4, false, 4],
  ["G8", "rough_hill", 4, false, 4],
  ["G9", "clear", 0, false, 0],
  ["G10", "clear", 0, false, 0],
  ["G11", "woods", 2, true, 0],
  ["H1", "woods", 2, true, 0],
  ["H2", "woods", 2, true, 0],
  ["H3", "clear", 0, false, 0],
  ["H4", "clear", 0, false, 0],
  ["H5", "clear", 0, false, 0],
  ["H6", "rough_hill", 4, false, 4],
  ["H7", "rough_hill", 4, false, 4],
  ["H8", "clear", 0, false, 0],
  ["H9", "clear", 0, false, 0],
  ["H10", "clear", 0, false, 0],
  ["H11", "woods", 2, true, 0],
  ["I1", "clear", 0, false, 0],
  ["I2", "woods", 2, true, 0],
  ["I3", "clear", 0, false, 0],
  ["I4", "clear", 0, false, 0],
  ["I5", "clear", 0, false, 0],
  ["I6", "clear", 0, false, 0],
  ["I7", "clear", 0, false, 0],
  ["I8", "clear", 0, false, 0],
  ["I9", "clear", 0, false, 0],
  ["I10", "clear", 0, false, 0],
  ["I11", "woods", 2, true, 0],
  ["J1", "woods", 2, true, 0],
  ["J2", "clear", 0, false, 0],
  ["J3", "clear", 0, false, 0],
  ["J4", "clear", 0, false, 0],
  ["J5", "clear", 0, false, 0],
  ["J6", "hill", 2, false, 2],
  ["J7", "clear", 0, false, 0],
  ["J8", "clear", 0, false, 0],
  ["J9", "clear", 0, false, 0],
  ["J10", "woods", 2, true, 0],
  ["J11", "woods", 2, true, 0],
  ["K1", "clear", 0, false, 0],
  ["K2", "woods", 2, true, 0],
  ["K3", "clear", 0, false, 0],
  ["K4", "clear", 0, false, 0],
  ["K5", "clear", 0, false, 0],
  ["K6", "hill", 2, false, 2],
  ["K7", "hill", 2, false, 2],
  ["K8", "clear", 0, false, 0],
  ["K9", "clear", 0, false, 0],
  ["K10", "woods", 2, true, 0],
  ["K11", "woods", 2, true, 0],
  ["L1", "clear", 0, false, 0],
  ["L2", "woods", 2, true, 0],
  ["L3", "clear", 0, false, 0],
  ["L4", "clear", 0, false, 0],
  ["L5", "clear", 0, false, 0],
  ["L6", "hill", 2, false, 2],
  ["L7", "hill", 2, false, 2],
  ["L8", "clear", 0, false, 0],
  ["L9", "clear", 0, false, 0],
  ["L10", "woods", 2, true, 0],
  ["L11", "woods", 2, true, 0],
  ["M1", "clear", 0, false, 0],
  ["M2", "woods", 2, true, 0],
  ["M3", "clear", 0, false, 0],
  ["M4", "clear", 0, false, 0],
  ["M5", "clear", 0, false, 0],
  ["M6", "clear", 0, false, 0],
  ["M7", "hill", 2, false, 2],
  ["M8", "clear", 0, false, 0],
  ["M9", "clear", 0, false, 0],
  ["M10", "woods", 2, true, 0],
  ["M11", "woods", 2, true, 0],
  ["N1", "clear", 0, false, 0],
  ["N2", "woods", 2, true, 0],
  ["N3", "clear", 0, false, 0],
  ["N4", "clear", 0, false, 0],
  ["N5", "clear", 0, false, 0],
  ["N6", "clear", 0, false, 0],
  ["N7", "clear", 0, false, 0],
  ["N8", "clear", 0, false, 0],
  ["N9", "clear", 0, false, 0],
  ["N10", "woods", 2, true, 0],
  ["N11", "woods", 2, true, 0],
  ["O1", "clear", 0, false, 0],
  ["O2", "woods", 2, true, 0],
  ["O3", "clear", 0, false, 0],
  ["O4", "clear", 0, false, 0],
  ["O5", "clear", 0, false, 0],
  ["O6", "clear", 0, false, 0],
  ["O7", "town", 1, false, 0],
  ["O8", "town", 1, false, 0],
  ["O9", "clear", 0, false, 0],
  ["O10", "woods", 2, true, 0],
  ["O11", "woods", 2, true, 0],
  ["P1", "clear", 0, false, 0],
  ["P2", "woods", 2, true, 0],
  ["P3", "clear", 0, false, 0],
  ["P4", "woods", 2, true, 0],
  ["P5", "clear", 0, false, 0],
  ["P6", "clear", 0, false, 0],
  ["P7", "town", 1, false, 0],
  ["P8", "clear", 0, false, 0],
  ["P9", "woods", 2, true, 0],
  ["P10", "woods", 2, true, 0],
  ["P11", "woods", 2, true, 0],
  ["Q1", "clear", 0, false, 0],
  ["Q2", "woods", 2, true, 0],
  ["Q3", "clear", 0, false, 0],
  ["Q4", "clear", 0, false, 0],
  ["Q5", "clear", 0, false, 0],
  ["Q6", "clear", 0, false, 0],
  ["Q7", "clear", 0, false, 0],
  ["Q8", "clear", 0, false, 0],
  ["Q9", "woods", 2, true, 0],
  ["Q10", "woods", 2, true, 0],
  ["Q11", "woods", 2, true, 0],
  ["R1", "hill", 2, false, 2],
  ["R2", "hill", 2, false, 2],
  ["R3", "clear", 0, false, 0],
  ["R4", "woods", 2, true, 0],
  ["R5", "clear", 0, false, 0],
  ["R6", "clear", 0, false, 0],
  ["R7", "clear", 0, false, 0],
  ["R8", "clear", 0, false, 0],
  ["R9", "rough_hill", 4, true, 2],
  ["R10", "rough_hill", 4, true, 2],
  ["R11", "woods", 2, true, 0],
  ["S1", "hill", 2, false, 2],
  ["S2", "hill", 2, false, 2],
  ["S3", "clear", 0, false, 0],
  ["S4", "clear", 0, false, 0],
  ["S5", "hill", 2, false, 2],
  ["S6", "clear", 0, false, 0],
  ["S7", "clear", 0, false, 0],
  ["S8", "hill", 2, false, 2],
  ["S9", "clear", 0, false, 0],
  ["S10", "woods", 2, true, 0],
  ["S11", "woods", 2, true, 0],
  ["T1", "clear", 0, false, 0],
  ["T2", "clear", 0, false, 0],
  ["T3", "clear", 0, false, 0],
  ["T4", "hill", 2, false, 2],
  ["T5", "clear", 0, false, 0],
  ["T6", "clear", 0, false, 0],
  ["T7", "clear", 0, false, 0],
  ["T8", "hill", 2, false, 2],
  ["T9", "woods", 2, true, 0],
  ["T10", "woods", 2, true, 0],
  ["T11", "woods", 2, true, 0],
  ["U1", "hill", 2, false, 2],
  ["U2", "clear", 0, false, 0],
  ["U3", "clear", 0, false, 0],
  ["U4", "clear", 0, false, 0],
  ["U5", "woods", 2, true, 0],
  ["U6", "clear", 0, false, 0],
  ["U7", "clear", 0, false, 0],
  ["U8", "clear", 0, false, 0],
  ["U9", "woods", 2, true, 0],
  ["U10", "woods", 2, true, 0],
  ["U11", "woods", 2, true, 0],
  ["V1", "clear", 0, false, 0],
  ["V2", "clear", 0, false, 0],
  ["V3", "clear", 0, false, 0],
  ["V4", "clear", 0, false, 0],
  ["V5", "woods", 2, true, 0],
  ["V6", "clear", 0, false, 0],
  ["V7", "clear", 0, false, 0],
  ["V8", "woods", 2, true, 0],
  ["V9", "woods", 2, true, 0],
  ["V10", "woods", 2, true, 0],
  ["V11", "woods", 2, true, 0],
  ["W1", "woods", 2, true, 0],
  ["W2", "clear", 0, false, 0],
  ["W3", "clear", 0, false, 0],
  ["W4", "clear", 0, false, 0],
  ["W5", "woods", 2, true, 0],
  ["W6", "woods", 2, true, 0],
  ["W7", "clear", 0, false, 0],
  ["W8", "clear", 0, false, 0],
  ["W9", "woods", 2, true, 0],
  ["W10", "woods", 2, true, 0],
  ["W11", "woods", 2, true, 0],
] as const satisfies readonly (readonly [
  HexCoordinate,
  HexTerrain["kind"],
  number,
  boolean,
  number,
])[];

export const FOREST_LINKS = [
  ["A1", "B1"],
  ["B1", "C1"],
  ["A4", "A5"],
  ["A4", "B4"],
  ["A5", "A6"],
  ["A5", "B4"],
  ["A5", "B5"],
  ["A6", "A7"],
  ["A6", "B5"],
  ["A6", "B6"],
  ["A7", "B6"],
  ["B4", "B5"],
  ["B4", "C4"],
  ["B4", "C5"],
  ["B5", "B6"],
  ["B5", "C5"],
  ["B5", "C6"],
  ["B6", "C6"],
  ["B6", "C7"],
  ["C4", "C5"],
  ["C4", "D3"],
  ["C5", "C6"],
  ["C5", "D5"],
  ["C6", "C7"],
  ["C6", "D5"],
  ["C6", "D6"],
  ["C7", "D6"],
  ["D3", "E3"],
  ["D3", "E4"],
  ["D5", "D6"],
  ["D5", "E5"],
  ["E3", "E4"],
  ["E3", "F3"],
  ["E4", "E5"],
  ["E4", "F3"],
  ["E4", "F4"],
  ["E5", "F4"],
  ["E5", "F5"],
  ["F3", "F4"],
  ["F4", "F5"],
  ["F4", "G5"],
  ["F5", "F6"],
  ["F5", "G5"],
  ["F6", "F7"],
  ["H1", "H2"],
  ["H1", "I2"],
  ["H2", "I2"],
  ["I2", "J1"],
  ["J1", "K2"],
  ["K2", "L2"],
  ["L2", "M2"],
  ["M2", "N2"],
  ["N2", "O2"],
  ["O2", "P2"],
  ["P2", "Q2"],
  ["D11", "E11"],
  ["E11", "F11"],
  ["F11", "G11"],
  ["G11", "H11"],
  ["H11", "I11"],
  ["I11", "J10"],
  ["I11", "J11"],
  ["J10", "J11"],
  ["J10", "K10"],
  ["J10", "K11"],
  ["J11", "K11"],
  ["K10", "K11"],
  ["K10", "L10"],
  ["K11", "L10"],
  ["K11", "L11"],
  ["L10", "L11"],
  ["L10", "M10"],
  ["L10", "M11"],
  ["L11", "M11"],
  ["M10", "M11"],
  ["M10", "N10"],
  ["M11", "N10"],
  ["M11", "N11"],
  ["N10", "N11"],
  ["N10", "O10"],
  ["N10", "O11"],
  ["N11", "O11"],
  ["O10", "O11"],
  ["O10", "P9"],
  ["O10", "P10"],
  ["O11", "P10"],
  ["O11", "P11"],
  ["P9", "P10"],
  ["P9", "Q9"],
  ["P9", "Q10"],
  ["P10", "P11"],
  ["P10", "Q10"],
  ["P10", "Q11"],
  ["P11", "Q11"],
  ["Q9", "Q10"],
  ["Q9", "R9"],
  ["Q10", "Q11"],
  ["Q10", "R9"],
  ["Q10", "R10"],
  ["Q11", "R10"],
  ["Q11", "R11"],
  ["R9", "R10"],
  ["R9", "S10"],
  ["R10", "R11"],
  ["R10", "S10"],
  ["R10", "S11"],
  ["R11", "S11"],
  ["S10", "S11"],
  ["S10", "T9"],
  ["S10", "T10"],
  ["S11", "T10"],
  ["S11", "T11"],
  ["T9", "T10"],
  ["T9", "U9"],
  ["T9", "U10"],
  ["T10", "T11"],
  ["T10", "U10"],
  ["T10", "U11"],
  ["T11", "U11"],
  ["U9", "U10"],
  ["U9", "V9"],
  ["U10", "U11"],
  ["U10", "V9"],
  ["U10", "V10"],
  ["U11", "V10"],
  ["U11", "V11"],
  ["V9", "V10"],
  ["V9", "W9"],
  ["V9", "W10"],
  ["V10", "V11"],
  ["V10", "W10"],
  ["V10", "W11"],
  ["V11", "W11"],
  ["W9", "W10"],
  ["W10", "W11"],
  ["V5", "W5"],
  ["V5", "W6"],
  ["W5", "W6"],
] as const satisfies readonly (readonly [HexCoordinate, HexCoordinate])[];

export const HILL_LINKS = [
  ["E6", "E7"],
  ["E6", "F5"],
  ["E6", "F6"],
  ["E7", "F6"],
  ["E7", "F7"],
  ["F5", "F6"],
  ["F5", "G6"],
  ["F6", "F7"],
  ["F6", "G6"],
  ["F6", "G7"],
  ["F7", "G7"],
  ["F7", "G8"],
  ["G6", "G7"],
  ["G6", "H6"],
  ["G7", "G8"],
  ["G7", "H6"],
  ["G7", "H7"],
  ["G8", "H7"],
  ["H6", "H7"],
  ["J6", "K6"],
  ["J6", "K7"],
  ["K6", "K7"],
  ["K6", "L6"],
  ["K7", "L6"],
  ["K7", "L7"],
  ["L6", "L7"],
  ["L6", "M7"],
  ["L7", "M7"],
  ["R1", "R2"],
  ["R1", "S1"],
  ["R1", "S2"],
  ["R2", "S2"],
  ["S1", "S2"],
  ["S5", "T4"],
  ["S8", "T8"],
  ["R9", "R10"],
] as const satisfies readonly (readonly [HexCoordinate, HexCoordinate])[];

function regions(
  coordinates: readonly HexCoordinate[],
  links: readonly (readonly [HexCoordinate, HexCoordinate])[],
): ReadonlyMap<HexCoordinate, string> {
  const neighbors = new Map(coordinates.map((c) => [c, [] as HexCoordinate[]]));
  for (const [a, b] of links) {
    if (!neighbors.has(a) || !neighbors.has(b) || !adjacentHexes(a).includes(b))
      throw new Error(`Invalid terrain link ${a}-${b}`);
    neighbors.get(a)!.push(b);
    neighbors.get(b)!.push(a);
  }
  const result = new Map<HexCoordinate, string>();
  for (const start of coordinates) {
    if (result.has(start)) continue;
    const queue = [start];
    result.set(start, start);
    for (let index = 0; index < queue.length; index++) {
      for (const next of neighbors.get(queue[index]!)!) {
        if (result.has(next)) continue;
        result.set(next, start);
        queue.push(next);
      }
    }
  }
  return result;
}

const forests = regions(
  rows.filter((r) => r[3]).map((r) => r[0]),
  FOREST_LINKS,
);
const hills = regions(
  rows.filter((r) => r[4] > 0).map((r) => r[0]),
  HILL_LINKS,
);

export const BOARD_TERRAIN: Readonly<Record<HexCoordinate, HexTerrain>> =
  Object.freeze(
    Object.fromEntries(
      rows.map(([coordinate, kind, defense, woods, hill_defense]) => [
        coordinate,
        Object.freeze({
          kind,
          defense,
          woods,
          hill_defense,
          forest_region: forests.get(coordinate) ?? null,
          hill_region: hills.get(coordinate) ?? null,
        }),
      ]),
    ),
  ) as Readonly<Record<HexCoordinate, HexTerrain>>;
