BEGIN;

CREATE TABLE IF NOT EXISTS service_games (
  game_id text PRIMARY KEY,
  position bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  state jsonb NOT NULL,
  record jsonb NOT NULL,
  deleted_at bigint,
  creation_id text
);
CREATE UNIQUE INDEX IF NOT EXISTS service_games_creation_id
  ON service_games (creation_id) WHERE creation_id IS NOT NULL;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM schema_migrations WHERE version = 4) THEN
    LOCK TABLE service_state IN EXCLUSIVE MODE;
    INSERT INTO service_games (game_id, position, state, record, deleted_at, creation_id)
    SELECT entry->>0, ordinal, entry->1->'state', (entry->1) - 'state',
           (entry->1->>'deletedAt')::bigint, entry->1->'creation'->>'creationId'
    FROM service_state,
         jsonb_array_elements(snapshot->'games') WITH ORDINALITY AS games(entry, ordinal);
    PERFORM setval(pg_get_serial_sequence('service_games', 'position'),
                   greatest(coalesce(max(position), 0), 1), count(*) > 0)
      FROM service_games;
    UPDATE service_state SET snapshot = jsonb_set(snapshot, '{games}', '[]'::jsonb);
    INSERT INTO schema_migrations (version) VALUES (4);
  END IF;
END $$;

COMMIT;
